// <auto-generated />
using System;
using eCommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace eCommerce.Infrastructure.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20240627174927_relacioniProduktKategori")]
    partial class relacioniProduktKategori
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCommerce.Infrastructure.Data.Kategorite", b =>
                {
                    b.Property<int>("Numri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numri"));

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Numri");

                    b.ToTable("Kategorite");
                });

            modelBuilder.Entity("eCommerce.Infrastructure.Data.Produktet", b =>
                {
                    b.Property<int>("Numri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numri"));

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriaNumri")
                        .HasColumnType("int");

                    b.HasKey("Numri");

                    b.HasIndex("KategoriaNumri");

                    b.ToTable("Produktet");
                });

            modelBuilder.Entity("eCommerce.Infrastructure.Data.Produktet", b =>
                {
                    b.HasOne("eCommerce.Infrastructure.Data.Kategorite", "Kategoria")
                        .WithMany("Produktet")
                        .HasForeignKey("KategoriaNumri");

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("eCommerce.Infrastructure.Data.Kategorite", b =>
                {
                    b.Navigation("Produktet");
                });
#pragma warning restore 612, 618
        }
    }
}
